version: '3.9'

# Development environment override
services:
  php:
#    depends_on:
#      mysql:
#        condition: service_started
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/srv/app:rw,cached
      - ./etc/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line 
      - /srv/app/var
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./etc/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro
  
#  mysql:
#    image: mysql:8
#    ports:
#      - "3308:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
#      MYSQL_USER: ${MYSQL_USER:-desksheet_connect}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-desksheet_connect}
#      MYSQL_DATABASE: ${MYSQL_DATABASE:-desksheet_connect}
#  
#volumes:
#  mysql_data:
