version: '3'

tasks:
  start:
    cmds:
      - $BIN_DOCKER_COMPOSE up --build -d
    desc: Build and start the containers

  build:
    cmds:
      - $BIN_DOCKER_COMPOSE build --pull --no-cache
    desc: Builds the Docker images

  up:
    cmds:
      - $BIN_DOCKER_COMPOSE up --detach
    desc: Start the docker hub in detached mode (no logs)
  
  down:
    cmds:
      - $BIN_DOCKER_COMPOSE down --remove-orphans
    desc: Stop the docker hub
  
  logs:
    cmds:
      - $BIN_DOCKER_COMPOSE logs --tail=0 --follow
    ignore_error: true
    desc: Show live logs

  ssh:
    cmds:
      - $BIN_DOCKER_COMPOSE exec php sh
    desc: Connect to the PHP FPM container
